apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: bindershare
  namespace: bindershare
spec:
  template:
    spec:
      containers:
        - image: us-west1-docker.pkg.dev/bindershare/cloud-run-source-deploy/bindershare/bindershare@sha256:be167935a7ce8fa67babb5fdd22229195d07c7a1c2bded18c87cd3240c4c8652
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
      containerConcurrency: 80
      timeoutSeconds: 500
